url: https://strongstartsforsuccess.org
baseurl: /

# Site settings
title: Strong Starts for Success
email: your-email@domain.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
background_image: hero-bg-2.jpg
mission: Provide safe, high-quality, affordable, community-based, holistic education for Liberia's youngest children.

# Team names, titles and social links
people:
- name: Hailey Breitenfeld
  pic: hailey_breitenfeld.jpg
  position: Founder and Executive Director
  description: Foobar
  modal-id: 1

- name: Makenna Breitenfeld
  pic: makenna_breitenfeld.jpg
  position: President
  description: Foobar
  modal-id: 2

- name: Precious Marshall
  pic: precious_marshall.jpg
  position: Secretary
  description: Foobar
  modal-id: 3

- name: Ada Rousso
  pic: ada_rousso.jpg
  position: Treasurer
  description: Foobar
  modal-id: 4

- name: Ettie King
  pic: ettie_king.jpg
  position: Member
  description: Foobar
  modal-id: 5

- name: Laurie Healy
  pic: laurie_healy.jpg
  position: Member
  description: Foobar
  modal-id: 6

- name: Marilyn Cahn
  pic: marilyn_cahn.jpg
  position: Member
  description: Foobar
  modal-id: 7

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: instagram
    url: https://www.instagram.com/strongstartsforsuccess
  - title: envelope
    url: mailto:foo@bar.com
  - title: facebook
    url: https://www.facebook.com/strongstartsforsuccess

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
