url: https://strongstartsforsuccess.org
baseurl: /

# Site settings
title: Strong Starts for Success
email: your-email@domain.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
background_image: hero-bg-2.jpg
mission: Provide safe, high-quality, affordable, community-based, holistic education for Liberia's youngest children.

# Team names, titles and social links
people:
- name: Hailey Breitenfeld
  pic: hailey_breitenfeld.jpg
  position: Founder and Executive Director
  description: Hailey holds a Master of Arts in International Education from New York University and a Bachelor of Arts in Psychology and a minor in Applied Developmental Psychology from University of California, Los Angeles (UCLA). She fell in love with West Africa in 2010 while studying abroad in Ghana and volunteering at Ghanaian public schools as she earned her bachelor’s degree from UCLA. Hailey has traveled to work in the education system in many African countries, including Ghana, Ethiopia, Tanzania, Kenya, Sierra Leone, and Liberia. Through her work and travels, she has enhanced her skills as an International Early Childhood Care and Education Professional by training teachers, developing curricula, teaching students, collecting and analyzing data, and co-directing a primary school. Hailey has always been drawn to the youngest children and carves out time to interact with them no matter her job description. She enjoys discovering and feeding their evident hunger for learning. The mission at Strong Starts for Success (S3) evolved from these experiences which opened the door for Hailey to pursue her passion for enabling the youngest children to have the best possible start in life. After years of learning, teaching and searching, Hailey is excited to create the first of S3’s developmentally appropriate early education centers in Harlandsville, Liberia. Now, the history of S<sup>3</sup> is just beginning, join us on the journey.
  modal-id: 1

- name: Makenna Breitenfeld
  pic: makenna_breitenfeld.jpg
  position: President
  description: "Makenna holds a Bachelor of Arts in Legal Studies from University of California, Santa Cruz and Bachelor of Science in Nursing from University of Miami. As president of the board, Makenna guides Strong Starts for Success, drawing from her experience as a consumer analyst, enterprise community manager, and registered nurse. Makenna is an avid biker, climber, outdoor enthusiast and advocate for education and knowledge sharing."
  modal-id: 2

- name: Precious Marshall
  pic: precious_marshall.jpg
  position: Secretary
  description: Foobar
  modal-id: 3

- name: Ada Rousso
  pic: ada_rousso.jpg
  position: Treasurer
  description: Foobar
  modal-id: 4

- name: Ettie King
  pic: ettie_king.jpg
  position: Member
  description: Foobar
  modal-id: 5

- name: Laurie Healy
  pic: laurie_healy.jpg
  position: Member
  description: Foobar
  modal-id: 6

- name: Marilyn Cahn
  pic: marilyn_cahn.jpg
  position: Member
  description: Foobar
  modal-id: 7

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: instagram
    url: https://www.instagram.com/strongstartsforsuccess
  - title: envelope
    url: mailto:foo@bar.com
  - title: facebook
    url: https://www.facebook.com/strongstartsforsuccess

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
